// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALkl9UxE_ZbCN6z15YienxeGd2LpQIz4Y',
    appId: '1:637361408443:web:7709a0df26d9a9a2591c9e',
    messagingSenderId: '637361408443',
    projectId: 'archive-92e98',
    authDomain: 'archive-92e98.firebaseapp.com',
    databaseURL: 'https://archive-92e98-default-rtdb.firebaseio.com',
    storageBucket: 'archive-92e98.firebasestorage.app',
    measurementId: 'G-7Z3YB7Q89V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDth34YGqzD6rmJv22rRoLpJ6XQGcUdBPk',
    appId: '1:637361408443:android:e86de0f13095ce7f591c9e',
    messagingSenderId: '637361408443',
    projectId: 'archive-92e98',
    databaseURL: 'https://archive-92e98-default-rtdb.firebaseio.com',
    storageBucket: 'archive-92e98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAknPU-ZapLHRmA0N3bIiq7YzplYniqWkA',
    appId: '1:637361408443:ios:6aacdfd673dcdda2591c9e',
    messagingSenderId: '637361408443',
    projectId: 'archive-92e98',
    databaseURL: 'https://archive-92e98-default-rtdb.firebaseio.com',
    storageBucket: 'archive-92e98.firebasestorage.app',
    iosBundleId: 'com.example.archive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAknPU-ZapLHRmA0N3bIiq7YzplYniqWkA',
    appId: '1:637361408443:ios:6aacdfd673dcdda2591c9e',
    messagingSenderId: '637361408443',
    projectId: 'archive-92e98',
    databaseURL: 'https://archive-92e98-default-rtdb.firebaseio.com',
    storageBucket: 'archive-92e98.firebasestorage.app',
    iosBundleId: 'com.example.archive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALkl9UxE_ZbCN6z15YienxeGd2LpQIz4Y',
    appId: '1:637361408443:web:8bc04e57a854e0b5591c9e',
    messagingSenderId: '637361408443',
    projectId: 'archive-92e98',
    authDomain: 'archive-92e98.firebaseapp.com',
    databaseURL: 'https://archive-92e98-default-rtdb.firebaseio.com',
    storageBucket: 'archive-92e98.firebasestorage.app',
    measurementId: 'G-CZ1G1FSZQP',
  );
}
